### ISSUE TITLE
Accessing a PRTG server that uses https and a self signed cert

### ISSUE THREAD

**Issue by beardymarrow** [jaydouble/PRTGNotificationHomeAssistant#4]
For anyone else coming across this, I added "verify_ssl: false" to the prtg.yaml file

```
sensor:
  - platform: rest
    name: PrtgSensors
    resource: !secret prtg-url
    verify_ssl: false
```
